#pragma once
//INTERSECCIONES CON LOS WIDGETS//RECTANGULOS CIRCULOS
//ITEM SELECCIONADO ES EL MAS CERCANO
//REVISAR EL TEMA DE GENERACION Y ACTUALIZACION DE GRAFICOS
//CREAR PRIMITIVA DE MARCO DE VENTANA// HECHAS, MEJORAR NORMALES
//SOLUCIONAR PROBLEMAS DE MEMORIA; MEMORY LEAKS!!!!!!
//MEJORAR LA FORMA QUE TENEMOS PARA SABER SI ESTAMOS CON LAS VR// REVISAR EVENT HANDLER VR

/////////////////////////////////////////////////////
//AÑADIR AGRUPACIONES DE MESHOBJECTS VERTEX-VERTEX EDGE-EDGE FACE-FACE



//REVISAR TODO EL SISTEMA DE RECOGIDA Y TRATAMIENTO DE LAS VARIABLES :D