#pragma once
//Add a way to recognize steps to make sound like crunshing sticks//

//REVISAR TODOS LO COMPONENTES PARA QUE LOS DRAWABLE SE DIBUJEN DURANTE SU DRAW FUNCTION//
//O EN LA CLASE BASE HACER REFERENCIA A UN NODO PRINCIPAL QUE ESTEN TODOS LOS COMPONENTES INCLUIDOS//

//CREAR UNA CLASE BASE PARA COMPONENTES QUE SE DEBAN MOSTRAR EN ALGUN MOMENTO DELANTE DE LA PANTALLA PARA DESPUES VOLVER A SU SITIO
//PENSAR LA MEJOR FORMA DE HACERLO
